# Generated by Django 4.2.4 on 2023-09-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_theme_post_themes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='_image',
        ),
    ]
