# Generated by Django 4.2.4 on 2023-09-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_image_post__image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_image',
            new_name='image',
        ),
    ]
